const express = require('express')
const dataTournament = express.Router()
const admTournamentController = require('../controllers/admTournamentController')
const matchController = require('../controllers/matchController')
const authentication = require('../middleware/authentication')

dataTournament.post('/',authentication.committeAuth,admTournamentController.createTournament)
dataTournament.get('/list',admTournamentController.listTournament)
dataTournament.get('/detail/:urlID',admTournamentController.detailTournament)
dataTournament.put('/update/:urlID',authentication.committeAuth,admTournamentController.updateTournament)
dataTournament.delete('/delete/:tournamentID',authentication.committeAuth,admTournamentController.deleteTournament)
dataTournament.post('/register/:urlID',authentication.userAuth,admTournamentController.registerTournament)
dataTournament.post('/team/register/:urlID',authentication.userAuth,admTournamentController.teamRegister)
dataTournament.put('/register/accept/:urlID',authentication.committeAuth,admTournamentController.acceptUser)
dataTournament.put('/register/reject/:urlID',authentication.committeAuth,admTournamentController.rejectUser)
dataTournament.get('/start/:urlID',authentication.committeAuth,admTournamentController.startTournament)
dataTournament.post('/match/detail/:urlID',admTournamentController.detailMatch)
dataTournament.put('/match1/:urlID',authentication.committeAuth,matchController.match1)
dataTournament.put('/match2/:urlID',authentication.committeAuth,matchController.match2)
dataTournament.put('/match3/:urlID',authentication.committeAuth,matchController.match3)
dataTournament.put('/match4/:urlID',authentication.committeAuth,matchController.match4)
dataTournament.put('/bronzeMatch/:urlID',authentication.committeAuth,matchController.bronzeMatch)
dataTournament.get('/committe/list',authentication.committeAuth,admTournamentController.tournamentByCommitte)
dataTournament.get('/headman/list',authentication.headManAuth,admTournamentController.tournamentBaseOnHeadman)
dataTournament.get('/myTournament', authentication.userAuth,admTournamentController.myTournament)
dataTournament.put('/ffa/match1/:urlID',authentication.committeAuth,matchController.match1Ffa)
dataTournament.put('/ffa/match2/:urlID',authentication.committeAuth,matchController.match2Ffa)
dataTournament.put('/ffa/match3/:urlID',authentication.committeAuth,matchController.match3Ffa)

module.exports = dataTournament